### ISSUE TITLE
Where can I find "instance.txt" file?

### ISSUE THREAD

**Issue by park-youngjae** [NeurAI-Lab/D-SSCD#1]
Thank you for wonderful change detection work.

I am trying to train your model with VL-CMU-CD dataset.

However, I am confronting this error.

**Traceback (most recent call last):
  File "./DSSCD/train.py", line 39, in <module>
    trainSSL(args, model, optimizer, criterion, args.writer, scheduler)
  File "/workspace/youngjae/BDA/0530_DSSCD/DSSCD/util/train_util.py", line 178,                                                                                                                         in trainSSL
    train_loader = trainloaderSimCLR(args)
  File "/workspace/youngjae/BDA/0530_DSSCD/DSSCD/util/train_util.py", line 49, i                                                                                                                        n trainloaderSimCLR
    transform = SimCLRTransform(args.img_size)
  File "/workspace/youngjae/BDA/0530_DSSCD/DSSCD/transforms/simclr_transform.py"                                                                                                                        , line 38, in __init__
    self.copy_paste_aug = copy_paste(sigma=3, affine=False, prob=0.5)
  File "/workspace/youngjae/BDA/0530_DSSCD/DSSCD/transforms/simclr_transform.py"                                                                                                                        , line 129, in __init__
    with open(self.instance_txt_path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/data/input/datasets/VL                                                                                                                        -CMU-CD/instance.txt'
root@e76133ed0122:/workspace/youngjae/BDA/0530_DSSCD# \--img_size 256 --n_proj 256 --hidden_layer 512 --output_stride 8 --pre_train False --m_backbone**        

Can you share the "instance.txt" file?

**Comment by Vijayraven95** [comment]
Hi @park-youngjae,
The instances.txt will contain all the list of changes between the images as a list. You only need instances.txt file if you want to use copy paste augmentation to train the model. However we didn't use this copy paste augmentation. You can comment it out and set the copy paste argument to false.
